### ISSUE TITLE
Reverse proxy: Port numbers in HTTP_X_FORWARDED_FOR should be ignored

### ISSUE THREAD

**Issue by jchristy40** [yellowtree/geoip-detect#124]
**Describe the bug**
Hello,

I have a Wordpress installation where it is known that we are using a reverse proxy. I have added the reverse proxy IP addresses to the 'whitelist' - and the correct client IP address is showing up in the HTTP_X_FORWARDED_FOR - however, the plugin continues to not detect the correct client IP. As you will see in the screenshot, the REMOTE_ADDR IP is added to the whitelist.

**Screenshots**
![image](https://user-images.githubusercontent.com/49081710/117495167-e501da80-af3a-11eb-8013-5043c8db72cd.png)

**Plugin configuration:**

Reverse Proxy set up? Yes

**Server:**
Plugin Version: 
PHP Version:
Which site cache plugin are you using (if any):  none
Any special server setup (Cloud? Docker? etc.): Reverse proxy on MS Azure

**Comment by jchristy40** [comment]
I was able to address the issue by using PHP to grab the correct IP, then passing the IP to the geoip_detect2_get_info_from_ip() function

**Comment by benjaminpick** [comment]
Oh I see, that's because of the port numbers ... I will add this fix to 
the plugin soon.

Benjamin

**Comment by benjaminpick** [comment]
Note to self:
IPv6 Port numbers have the format  `[::1]:8080`

**Comment by benjaminpick** [comment]
I just released a Beta Version to fix this, can you try it please?
https://github.com/yellowtree/geoip-detect/wiki/Beta-Testing

**Comment by benjaminpick** [comment]
Fixed in 4.2.0
