### ISSUE TITLE
Permalink for query

### ISSUE THREAD

**Issue by mercadeoshop** [yellowtree/geoip-detect#135]
Hello, i would like to know if is possible create a page with permalink for show the info of the ip, something like this:

www.domain/lookup/1.1.1.1

And the plugin show the info of the IP in the page

Thanks in advance

**Comment by benjaminpick** [comment]
Yes it is possible to code this. However, make sure the terms of use of 
the data source allow this, I vaguely remember there are special 
conditions for this use case (public display of the data) at least for 
the Maxmind sources ...

**Comment by benjaminpick** [comment]
Closing this as this is not something the plugin can solve for all users.
