### ISSUE TITLE
Potential security issue with AbstractUnicodeString.php - Generic.Hidden.Code.2

### ISSUE THREAD

**Issue by simon-olsen** [yellowtree/geoip-detect#145]
**Describe the bug**
We installed into our WP VIP hosting (Automattic's enterprise hosting) and we got a warning about line 37 in `plugins/geoip-detect/vendor/symfony/string/AbstractUnicodeString.php` saying it was a potential security risk: Generic.Hidden.Code.2

```
private const ASCII = "\x20\x65\x69\x61\x73\x6E\x74\x72\x6F\x6C\x75\x64\x5D\x5B\x63\x6D\x70\x27\x0A\x67\x7C\x68\x76\x2E\x66\x62\x2C\x3A\x3D\x2D\x71\x31\x30\x43\x32\x2A\x79\x78\x29\x28\x4C\x39\x41\x53\x2F\x50\x22\x45\x6A\x4D\x49\x6B\x33\x3E\x35\x54\x3C\x44\x34\x7D\x42\x7B\x38\x46\x77\x52\x36\x37\x55\x47\x4E\x3B\x4A\x7A\x56\x23\x48\x4F\x57\x5F\x26\x21\x4B\x3F\x58\x51\x25\x59\x5C\x09\x5A\x2B\x7E\x5E\x24\x40\x60\x7F\x00\x01\x02\x03\x04\x05\x06\x07\x08\x0B\x0C\x0D\x0E\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C\x1D\x1E\x1F";
```

What does this code do? The warning specifically flagged the following in the above code: `\x65\x69\x61\x73\x6E\x74\x72\x6F\x6C\x75\x64`

**Plugin configuration:**
Currently used datasource: HostIP.info Web-API
Reverse Proxy set up? No

**Server:**
Plugin Version: 4.2.3
PHP Version: 7.4
Which site cache plugin are you using (if any): None
Any special server setup (Cloud? Docker? etc.): WP VIP with Varnish

**Comment by benjaminpick** [comment]
This is a false positive - because it's not code, it's a list of valid Unicode points.
See https://wordpress.org/support/topic/vaultpress-security-scan-warning/

**Comment by simon-olsen** [comment]
OK thanks for letting us know. 😃
