### ISSUE TITLE
Custom Header Name for Data Source "Special Hosting Providers"

### ISSUE THREAD

**Issue by din4711** [yellowtree/geoip-detect#180]
**Is your feature request related to a problem / specific use-case? Please describe.**
Some WAF offers the possibility to add the country to the header. Therefore the information which country the user is in is already provided.
`WAF-Country: DE`

**Describe the solution you'd like**
If a special header is set to a country the plugin could skip the ipcheck against the database and use whatever is found in the header.

- [ ] Add an option to activate this and to define the header name (here WAF-Country)
- [ ] Check if there is a valid country in the header and if yes set this country and skip the IP check

Possible texts for the options:
Some Web Application Firewalls offer to add headers to the request and determining the person location. Please select this checkbox if you want to check a defined header for a country value (country code must be in XYZ formatting). If this check is not successfully the normal IP check will be done

**Comment by benjaminpick** [comment]
Thank you - I will make the AWS / Cloudflare Data source more generic to make this possible.

**Comment by benjaminpick** [comment]
I implemented it using a wordpress filter, is this fine for you?
