### ISSUE TITLE
AJAX Endpoint

### ISSUE THREAD

**Issue by benjaminpick** [yellowtree/geoip-detect#19]
`admin-ajax.php?action=geoip_detect2_get_info_from_current_ip&locales=fr,en`

should return the JSON data.

**Comment by benjaminpick** [comment]
Difficulty: everybody could potentially use the service (not allowed for paid file), and we cannot avoid it with nonces when the goal is to get cached pages customized. So:
1) this must be opt-in
2) add a secret parameter
3) check the referer.

**Comment by alaninteractive** [comment]
Sounds great. I'm using http://freegeoip.net/ as a workaround, but it seems a little flakey. Thanks

**Comment by benjaminpick** [comment]
I have started the work on the ajax branch. TODO:
[ ] Filling in empty attributes so that the JSON structure is always the same (unit tests)
[ ] Errors should always be JSON
[ ] (post 2.6.0) Make shortcodes work with caching via JS by enqueuing a JS-File and replace placeholder in the HTML (as global option? as shortcode param?)

**Comment by alaninteractive** [comment]
Woop! Thanks Benjamin

**Comment by benjaminpick** [comment]
Basic support released in 2.11.0 - Further work in #60
