### ISSUE TITLE
WP_Filesystem call with $allow_relaxed_file_ownership = true

### ISSUE THREAD

**Issue by anthonyeden** [yellowtree/geoip-detect#206]
**Describe the bug**

On a filesystem where the tmp directory is writable, but the file owner of file.php is different to the owner of files in the tmp directory, GeoIP Detect will fail to download the MaxMind DB with the error message "WP Filesystem could not be initialized (does not support FTP credential access. Can you upload files to the media library?)".

This is owing to the checks in https://developer.wordpress.org/reference/functions/get_filesystem_method/

This can be fixed by calling WP_Filesystem with $allow_relaxed_file_ownership = true

**Screenshots**
N/A

**Plugin configuration:**
Currently used datasource: GeoLite2 City database
Reverse Proxy set up? Yes

**Server:**
Plugin Version: 5.0.0
PHP Version: 8.0
Which site cache plugin are you using (if any): N/A
Any special server setup (Cloud? Docker? etc.): AWS Linux 2

**Comment by benjaminpick** [comment]
This should be fixed in feecb0e . I have released a new Beta, can you try it out please?

**Comment by anthonyeden** [comment]
Sorry for never getting back to you. This fixed it up nicely.
