### ISSUE TITLE
errors on config to use pre-existing,  local fs .mmdb data

### ISSUE THREAD

**Issue by pgnd** [yellowtree/geoip-detect#269]
i've installed

```
wp-cli core version
	6.6.1

wp-cli plugin status geoip-detect
	Plugin geoip-detect details:
	    Name: Geolocation IP Detection
	    Status: Active
	    Version: 5.4.0
	    Author: Yellow Tree (Benjamin Pick)
	    Description: Provides geographic information detected by an IP adress.
```

i source geolite2 data from a licensed MaxMind account

i already have
```
ls -al /usr/share/GeoIP/
	-rw-r--r--    1 root root 8.3M Aug 13 07:11 GeoLite2-ASN.mmdb
	-rw-r--r--    1 root root  50M Aug 13 07:11 GeoLite2-City.mmdb
	-rw-r--r--    1 root root 6.9M Aug 13 07:11 GeoLite2-Country.mmdb
```

the data's sourced _once_ for my lan -- on my edge router box -- and is synced from there to each machine.
(recommended approach by MaxMind to _not_ abuse DL limits)

for this plugin, i'd like to use those preexisting files for data source.

@ plugin config, I choose data source:
```
[X] Maxmind City or Country database (Manual download & update)
```

leave
```
Account ID: 0
License key:
```
since there's no need to connect or provide the data to MaxMind (it's all done at the edge router, as above).

set
```
Filepath to mmdb-file:  /usr/share/GeoIP/GeoLite2-Country.mmdb
```

and `Save`

the page returns a number of warnings/errors,

---
**@ https://example.com/wp/wp-admin/options-general.php?page=geoip-detect%2Fgeoip-detect.php**

The license key is at least 16-char long. Are you sure this is the right key? Do not use the "unhashed format" when generating the license key. This key is 0 chars long.This is not a valid Maxmind Account ID.

Selected data source: GeoLite2 Country database

/srv/wp/web/app/plugins/geoip-detect/data-sources/manual.php:303:string '/srv/wp/vendor/vlucas/phpdotenv/src/Store/File/Reader.php' (length=113)

Database file: ../../../../../../../usr/share/GeoIP/GeoLite2-Country.mmdb
Database last updated: August 13, 2024 11:11 am
Database generated: August 9, 2024 7:13 pm

Warning: These Maxmind files were loaded from other plugins:
  -  /srv/wp/vendor/vlucas/phpdotenv/src/Store/File/Reader.php (different version)
(This can result in errors.)

---

what's the correct method to cleanly use pre-existing local filesystem mmdb data?
are there .env/functions.php overrides? or other config?

thx.

**Comment by benjaminpick** [comment]
Hi! 
The reason the plugin is asking for the Maxmind credentials is the automatic update of the CCPA / Privacy Exclusion API. As per Maxmind EULA, you need to make sure you are not using information from the IPs listed there: https://www.maxmind.com/en/accounts/146803/do-not-sell-requests

https://dev.maxmind.com/geoip/privacy-exclusions-api

That's why I made it a required field...

**Comment by benjaminpick** [comment]
The mmdb files are updated once a month. With the Privacy API, the IP can be exluded earlier. The plugin is calling the API once per day. This can be disabled with the filter `geoip_detect2_maxmind_ccpa_enabled`:

Add e.g. to your theme's function.php:
```php
add_filter('geoip_detect2_maxmind_ccpa_enabled', '__return_false');
``

**Comment by benjaminpick** [comment]
Closing this issue as I don't see any open issues here anymore, feel free to re-open if there is still something ...
