### ISSUE TITLE
Not detecting user's IP when user is not logged in to WordPress site

### ISSUE THREAD

**Issue by ghost** [yellowtree/geoip-detect#43]
Hi all,

The plugin is working fine when I am logged in to my wordpress website, and it is able to detect my IP as well as location country.

However when trying to surf the site when I'm not logged in or via private browsing, the plugin is unable to detect my IP address. Hence it retrieves the (I assume) default value which is the IP address of the server. 

Could someone help me with this issue please?

Thank you.

**Comment by jubjubjo** [comment]
@benjaminpick 

Hi Benjamin, 

Thank you for your reply!

I am using a plugin called: WP Fastest Cache; and I am also using Cloudflare. I am unsure if these plugins would have any impact on the performance of detecting a user's IP - so if you could help me with it, that would be great. :)

Here are more details for your reference:
- shortcode used: [geoip_detect2 property="country"]
- data source used: Maxmind GeoIP2 Lite City

Thanks for your help once again :)

**Comment by jubjubjo** [comment]
@benjaminpick 

Hey Benjamin, any updates on this please? Would greatly appreciate your help on this. 

Thank you.

**Comment by benjaminpick** [comment]
Did you check if the cloudflare source is working ? https://support.cloudflare.com/hc/en-us/articles/200168236-What-does-CloudFlare-IP-Geolocation-do-
Otherwise you will need to exclude the URLs that need Geo-Detection in Cloudflare.

**Comment by benjaminpick** [comment]
I recommend using the AJAX mode now for setups like this.
