### ISSUE TITLE
GitHub Updater sees this plugin as 2 different plugins.

### ISSUE THREAD

**Issue by afragen** [yellowtree/geoip-detect#55]
In order for GitHub Updater to correctly function, a plugin that exists both within the dot org directory and in GitHub must use the same plugin slug. In this plugin’s case, when installed from dot org the slug will be`geoip-detect` and if installed from GitHub the slug will be `wp-geoip-detect`.

As the `GitHub Plugin URI: https://github.com/yellowtree/wp-geoip-detect` in the plugin’s headers look to the GitHub repository as the source for updates and my show an update. If the GitHub Update is used then it is likely that 2 copies of the plugin will be installed.

The solution is to change the GitHub repository name to match the dot org slug or remove the header from the version pushed to dot org. GitHub does a good job with redirects.

https://github.com/afragen/github-updater/issues/746

**Comment by benjaminpick** [comment]
Thanks for the heads-up - the Repo is renamed now. 

(I don't see an easy fix for the beta versions, though, as tagging them all would lead to whole lot of them - instead I try to keep the master branch stable.)

**Comment by afragen** [comment]
I usually just use a different branch for development/beta stuff. If the user is on that branch GHU will update accordingly.
