### ISSUE TITLE
CF7: New shortcode for text input with a default value from geoip-detect

### ISSUE THREAD

**Issue by levolutionniste** [yellowtree/geoip-detect#57]
Hi! thanks for the great job. I can easily display a combo box with the country of the user preselected in worpress. But I woulld like to do the same with the city. This is the construction to have the country list with the user's one preselected.  [geoip_detect2_countries text-ville id:contact-ville class:form-control lang:fr include_blank default:US]

What could be the equivalent for cities. The goal is to retrieve the user city no matter his manual selection?

**Comment by benjaminpick** [comment]
It is a bit unclear what you final goal is. Do you use WPCF7 or not? Do you want a select box or a input box?

`<input type="text" value="[geoip_detect2 property="city"]" />` should work.

But if the user should not be able to modify it, https://github.com/yellowtree/geoip-detect/wiki/API-Documentation#insert-the-geoinfos-of-the-user-into-the-email-text might be more appropriate.

**Comment by levolutionniste** [comment]
Yes I use contact form 7.
I want an input text.
Will be ok, to see how to display the select box also.
Thanks

**Comment by benjaminpick** [comment]
Sorry I still don't get what you need. If you prefer, you can write in French as well.

**Comment by levolutionniste** [comment]
Bonjour. J'aimerai bien être en mesure de remplir automatiquement un champ texte contact form 7 avec la ville de l'internaute en m'appuyant sur votre plugin. Comment faire?

Merci.

**Comment by benjaminpick** [comment]
Ah d'accord. Oui je vais ajouter un raccourci dans le style `[geoip_detect2_text property:city lang:fr id:id class:class default:Paris]`.

**Comment by benjaminpick** [comment]
Le code est bon maintenant, je pense. Il serait bien si vous pouvez tester ...
https://github.com/yellowtree/geoip-detect/archive/master.zip

Docs: https://github.com/yellowtree/geoip-detect/wiki/API-Documentation#create-a-text-input-that-is-prefilled-with-a-geodetected-property

**Comment by levolutionniste** [comment]
Hi, sorry for the delay. But I still have problem. No errors this time but no city is displayed unless I set de default value.
What I did:
-Uninstall the previous version
-Download the one in the link you provide up (version 2.10)
-Install it on my wordpress website
-Try the lookup and this is the result 

Key | Value | Shortcode equivalent
-- | -- | --
$record->city->name |   | [geoip_detect2 property="city"]
$record->mostSpecificSubdivision->isoCode |   | [geoip_detect2 property="mostSpecificSubdivision.isoCode"]
$record->mostSpecificSubdivision->name |   | [geoip_detect2 property="mostSpecificSubdivision"]
$record->country->isoCode | CM | [geoip_detect2 property="country.isoCode"]
$record->country->name | Cameroun | [geoip_detect2 property="country"]
$record->location->latitude | 6 | [geoip_detect2 property="location.latitude"]
$record->location->longitude | 12 | [geoip_detect2 property="location.longitude"]
$record->continent->code | AF | [geoip_detect2 property="continent.code"]
$record->location->timeZone | Africa/Douala | [geoip_detect2 property="location.timeZone"]

-So, as I tried to apply this (strictly): [geoip_detect2_text_input property:city lang:fr id:id class:class] without success, I tried this (customized to my other  "contact form 7" 's fields):
[geoip_detect2_text_input property:city lang:fr id:contact-ville class:form-control]. But it was also unsuccessful.

-Then I tried with country thinking I was not seeing the city because the lookup also, did not show my city:
[geoip_detect2_text_input property:country lang:fr id:contact-ville class:form-control]. Whithout any success, apart seeing the default value when I add it.

-I also try with the location.timezone : no success either.
[geoip_detect2_text_input property:location.timezone lang:fr id:contact-ville class:form-control]

So that's where I am. Thnak you for all your efforts and support.

**Comment by levolutionniste** [comment]
Bonjour, désolé pour le délais.

L'API fonctionne très bien pour les pays mais pas pour les villes. Pour ces
dernières quelles la détection ne se fait pas automatiquement.

D'ailleurs le lookup en back office Wordpress n'affiche pas la ville.
[image: image.png]

[image: image.png]
[image: image.png]

Merci.
---
KENMEUGNE TCHUINKAM Romuald Franck (+237) 695 28 93 02 / 675 70 37 54


Le ven. 18 janv. 2019 à 19:12, Benjamin Pick <notifications@github.com> a
écrit :

**Comment by benjaminpick** [comment]
Désolé, je ne peux pas ajouter les informations sur les villes, ca depend sur la base de données de Maxmind. Par exemple, si vous entrez la IP "88.64.140.3" ca devrait afficher une ville. Maxmind ne connait pas toujours les villes, et peut-être les bases de données payées sont plus précises.

**Comment by levolutionniste** [comment]
D'accord merci pour les éléments d'informations.

Romuald Franck
