### ISSUE TITLE
Improve AJAX support

### ISSUE THREAD

**Issue by benjaminpick** [yellowtree/geoip-detect#60]
So far, this is implemented in 2.11.0:

- JSON Endpoint
- JS code to access the record of this endpoint
- (Hidden feature) Body class via AJAX

Use this bug report to discuss any improvement ideas.

- [x] Add cookie cache for server response

Roadmap:
1. Next months - Stabilize API (e.g. - I'm not sure if `record.get()` should support both camelCase and underscore_property), remove Beta flag
2. Sometime in the future - Make it possible that the current shortcodes work automatically also via AJAX. (It will be hard to implement all properties. But I don't want to implement only some and get support requests. That's why it will probably take quite a while.)

**Comment by benjaminpick** [comment]
- [ ] Add cookie cache for server response

**Comment by michaelkrieger** [comment]
The requirement for jQuery vs raw javascript limits the performance of this to requiring a bulky jquery file.  Following the likes of [Bootstrap](https://github.com/twbs/bootstrap/issues/28342) removing jquery's heavy-weight payload.

It should ideally be a **Native XMLHttpRequest** after prototyping is completed.

**Comment by benjaminpick** [comment]
Hm, yes that would be better, I might do it at some point - you are
welcome to send a pull request if you like ...

**Comment by benjaminpick** [comment]
The jQuery dependency was removed. I will declare the AJAX API stable soon.

**Comment by benjaminpick** [comment]
With 4.0 AJAX support (as outlined above) will be complete, see beta branch.
