### ISSUE TITLE
Not detecting country

### ISSUE THREAD

**Issue by dskurth** [yellowtree/geoip-detect#62]
The system does not seem to be detecting the country, based on using the HostIP.info Web-API.  all I need is the country of the user, nothing else, but the PHP sample code (which seemed perfect), only results in default listing.  What would you suggest?

This is the code I am using:
`
if (function_exists('geoip_detect2_get_info_from_current_ip')) 
    {
	$userInfo = geoip_detect2_get_info_from_current_ip();
	$countryCode = $userInfo->country->isoCode;
	switch ($countryCode) {
		case 'DE':
	      $SearchLat  = 50.00;  $SearchLong= -65.00;	    // Default location atlantic ocean
            $ZoomLevel  = 4;
		break;
		case 'US':
		   $SearchLat = 38.41299;  $SearchLong= -102.8106317;	    // Default location - Center of United States
	       $ZoomLevel  = 4;
		break;

		default:
		  $SearchLat = 38.41299;  $SearchLong= -102.8106317;	    // Default location - Center of United States
	      $ZoomLevel  = 4;
	}
`

**Comment by benjaminpick** [comment]
The latitude/longitude are determined by geonames - check the newest plugin version to see the property names (location->latitude or so).

You can try other IPs in the backend.
