### ISSUE TITLE
[QUESTION] Is there a function to get a list of all the countries from the database?

### ISSUE THREAD

**Issue by mersadk** [yellowtree/geoip-detect#66]
Hi,

I'm implementing plugin that will offer user an option to choose countries from a list of countries. I would like to know if there is a function to get a list of all the countries in a database as array, ideally with ISO code and full name?

**Comment by benjaminpick** [comment]
Yes: 

```php
$countryInfo = new YellowTree\GeoipDetect\Geonames\CountryInformation();
$countries = $countryInfo->getAllCountries($locales);
$moreInfo = $countryInfo->getInformationAboutCountry('de')
```

**Comment by benjaminpick** [comment]
If you want to show a select box, you can use this shortcode  
They also work without CF7:

https://github.com/yellowtree/geoip-detect/wiki/API:-Shortcodes#create-a-select-input-with-all-countries
