### ISSUE TITLE
FAQ entry regarding GeoLite2 license is out of date

### ISSUE THREAD

**Issue by 2shortplanks** [yellowtree/geoip-detect#70]
Due to upcoming data privacy regulations, MaxMind are making significant changes to how users access free MaxMind GeoLite2 databases starting December 30, 2019. The databases will continue to be available without charge and for redistribution. However, you will be required to create an account and use a license key to download the databases, and agree to a new EULA that addresses applicable data privacy regulations.

Learn more on the MaxMind blog: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/.

Mark Fowler
MaxMind

**Comment by benjaminpick** [comment]
Thanks for the heads-up. I will create an update of the plugin soon. However, 30 Dec effectively means that most of the users will experience an interruption of service as they need to install the update manually. But I guess it is not possible for you to delay the deadline for a month or so?

**Comment by 2shortplanks** [comment]
We are sorry, for legal reasons we will not be able to delay the deadline.

We apologize for not providing more notice. The CCPA was finalized in October, and it contains a number of ambiguities, particularly as it relates to our products. To arrive at our current interpretation, it has taken many weeks of working with privacy lawyers, following discussions in the privacy community, and observing actions other companies have taken. We're sorry for the timing, appreciating the frustration it causes, and wish we could have provided more notice.

**Comment by benjaminpick** [comment]
Progress:

- [x] Update FAQ
- [ ] Update Readme
- [x] Update automatic update code
- [ ] Update first-install notice

**Comment by benjaminpick** [comment]
The version 3.0 is out now – I couldn’t test it though as invalid licence keys do not throw any error. Probably we will know more tomorrow

**Comment by benjaminpick** [comment]
Fixed with 3.0
