### ISSUE TITLE
This plugin is slowing down website speed.We can store country data in database instead of a file

### ISSUE THREAD

**Issue by dhimananju** [yellowtree/geoip-detect#71]
This plugin is slowing down website speed.We can store country data in database instead of a file

**Comment by benjaminpick** [comment]
- Did you measure the performance impact? How often do you do a lookup in the file per web-page request?
- If you want to send a Pull Request for performance optimization, you are welcome. Probably these optimizations regard more the Maxmind library than my plugin, though.

**Comment by najeeboffice** [comment]
Yes due to this Google PageSpeed FCP value is 3+. Can we do something to fix this?

**Comment by benjaminpick** [comment]
AJAX mode (with a site cache) should improve performance.
