### ISSUE TITLE
Add a country-specific CSS class to the <body>-Tag

### ISSUE THREAD

**Issue by AaronG33K** [yellowtree/geoip-detect#72]
After updating this plugin my pages go blank white when this option is enabled. 

When inspecting the source, it looks like the entire body tag is void of any classes all together.

**Comment by benjaminpick** [comment]
I cannot reproduce this issue - I can see the body classes fine. (Except if I enable AJAX as well, because then the body classes are added via JS, not in the HTML).

Can you disable all other plugins to make sure this plugin is the cause (maybe you upgraded a different plugin at the same time)?

**Comment by benjaminpick** [comment]
Closed for inactivity. If the problem persist, try to use the AJAX body classes instead.
