### ISSUE TITLE
How to troubleshoot errors?

### ISSUE THREAD

**Issue by Mulegoat** [yellowtree/geoip-detect#75]
Hi there,

I'm using this plugin on a site along with the maxmind precision web service for price localization. I'm usin gthe php syntax to detect geoip info and if user in is EU or US I use the Open Exchange rate api to convert price fields. 

This works really well most of the time however there are occasions when pages disply price info in USD on UK based IP addresses. I'd like to know where and how I can debug this issue if possible and what information I need from my server logs?

Also, I'd like to know if I'm actually using this plugin correctly :) Here is the code I use:

`<?php
	if (function_exists('geoip_detect2_get_info_from_current_ip')) {
		$userInfo = geoip_detect2_get_info_from_current_ip();

			if ($userInfo->country->isoCode =='GB')  {

			get_template_part('templates/get-price-gbp');
			
		} else {
      // Query IP and return price in eithe EU or USD
			get_template_part('templates/get-price-conversion');	
		}

	} else {
		// If service unavailabe display GBP
		get_template_part('templates/get-price-gbp');

	}
?>
`

Get Price Conversion Template:

`<?php 

  $price = get_field("price");

  if( $price ) {

		if (function_exists('geoip_detect2_get_info_from_current_ip')) {
			$userInfo = geoip_detect2_get_info_from_current_ip();

				if ($userInfo->continent->code == 'EU' && $userInfo->country->isoCode !=='GB' )  {
				echo '€';	
				echo get_conversion( 'number='. $price . '&from=gbp&to=eur' );

			} elseif ($userInfo->continent->code == 'NA') {

				echo '$';	
				echo get_conversion( 'number='. $price . '&from=gbp&to=usd' );

			} else {

				echo '£';
				echo $price;

			}

		} 

	} else {

			echo 'Price TBC';
			
		}
?>
`

I realize that get_conversion is an openexchagerate function but I'm working on the assumption that prices wouldn't be getting converted to dollars unless there was an error in the geoip lookup?

If anybody has used these services and has any useful info that would be awesome. Many thanks in advance

**Comment by benjaminpick** [comment]
I have created a guide for Troubleshooting:

https://github.com/yellowtree/geoip-detect/wiki/Troubleshooting

**Comment by benjaminpick** [comment]
If the problem persists, feel free to re-open.
