### ISSUE TITLE
I want to use ISO code 3 in whole plugin files for country.

### ISSUE THREAD

**Issue by bhruge** [yellowtree/geoip-detect#77]
@benjaminpick  I Use the GeoIP detection plugin for WordPress. I want to use ISO code(3 Digits) for country-code like **'IND'**
Right now my plugin uses 2 digit ISO code.
And I use Special Hosting Providers (Cloudflare) to detect country automatic in my website.

**Comment by benjaminpick** [comment]
This will be possible in 3.1.1 : 

`$record->extra->isoCode3` or `[geoip_detect2 property="extra.countryIsoCode3"]`
