### ISSUE TITLE
New Datasource: Fastah IP API 

### ISSUE THREAD

**Issue by s8mathur** [yellowtree/geoip-detect#81]
Hello, 

Would contributions be welcome for an [additional REST API](https://aws.amazon.com/marketplace/pp/B084VR96P3) as a data source/backend? 

I am the developer of the above API. We at Fastah intend to keep it as a paid offering with a credible support plan (there is a no-cost, 30-day trial available) 

How it compares to [what's already part of YellowTree](https://github.com/yellowtree/geoip-detect/wiki/FAQ#which-data-source-should-i-choose)
a) mobile IPs coverage - constantly being enhanced, and includes IPv6 deployments by mobile carriers
b) security in transit - HTTPS with TLS1.2+ as the only transport option
c) performance: HTTP/2 out of the box to enable request/response multiplexing. Open to adding in-memory caching to the client-side. 

Please let me know if this would be a good idea :)

Sid

**Comment by benjaminpick** [comment]
Sounds good!

Can you send me an example response (which fields are you filling) ? You
can also send it privately to wp-geoip-detect posteo.de

Could you create me a test account for 50 requests / months that doesn't
expire after the trial ?

Benjamin

**Comment by s8mathur** [comment]
Hey Benjamin, 

I have picked this up again, current work-in-progress branch is [here](https://github.com/fastah/geoip-detect/commits/develop). Any guidance on which HTTP client to use? Is it OK to require availability of PHP-Curl and associated `curl_init()`? 

The Fastah API endpoint requires TLS 1.2 and recommends HTTP/2 for performance (and concurrency) , so it would be desirable for this data-provider implementation to use the best possible HTTP/2 client that can be reasonably packed with the plugin or expected to be available in the host installation. Recommendations? :) 

About your example response question, the [REST API response ](https://docs.getfastah.com/docs/quick-start) is as follows: 
```json
{
	"ip": "200.38.122.55",
	"isEuropeanUnion": false,
	"locationData": {
		"countryName": "Mexico",
		"countryCode": "MX",
		"cityName": "Mexico City",
		"cityGeonamesId": 3530597,
		"lat": 19.44,
		"lng": -99.14,
		"tz": "America/Mexico_City",
		"continentCode": "NA"
	}
}
````
Note that only 'en' locale is currently returned. Would be this be good enough to start with? 

Will send you a trial key too! :)

**Comment by benjaminpick** [comment]
Hi,

great to hear!

Please use the HTTP functions by wordpress:

https://developer.wordpress.org/apis/handbook/making-http-requests/

HTTP/2 is normally implemented in libcurl, so it might not be available
on every machine. My suggestion is to have the datasource work on every
host, and then have the possibility to improve performance with HTTP/2
(e.g. an opt-in option of the datasource).

Here is something to get you started:

|if (!defined('CURL_HTTP_VERSION_2_0')) {
define('CURL_HTTP_VERSION_2_0', 3); }|

|add_action('http_api_curl', function($handle ){ // Enable HTTP/2|
||curl_setopt($handle, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2_0); |},
10);|

En locale is ok, yes, not all sources have translated names.

**Comment by benjaminpick** [comment]
This is how HTTP/2 support of the curl library can be detected:

https://github.com/guzzle/guzzle/issues/1249

if  (curl_version()["features"] &CURL_VERSION_HTTP2  !==0) {

}

**Comment by s8mathur** [comment]
I can definitely use the core Wordpress HTTP functions for maximum portability, documentation is great. 
Since their core library (above) makes no mention of HTTP/2 support, I will need a parallel Curl implementation in addition to the former?

**Comment by benjaminpick** [comment]
I have looked at your code - yes it's going in a good direction, keep the stream_context. You will need to adjust the error messages accordingly (wp_get_remote should always so the plugin is not requiring curl per se - HTTP/2 support is not required but recommended etc.)

Instead of letting them choose an option that is not available on their server, you can show a message "HTTP/2 is not supported on your server. (needed libcurl version: )" and grey out the option. (It is still possible that the option is on and no HTTP/2 support, because the website might be developed locally and then pushed onto another machine.)

**Comment by s8mathur** [comment]
Understood, thank you. 
The core HTTP classes seems to [auto-detect Curl](https://github.com/WordPress/WordPress/blob/5.6/wp-includes/class-http.php#L507-L548), so one implementation is what I will do.

**Comment by s8mathur** [comment]
Hey @benjaminpick  
A pull request is ready for your review. 
Additionally, I have sent you an invite email to the Fastah API Developer Console which allows you to fetch API keys associated a subscription (you may rotate keys, see API success stats, origin, latency etc via this portal). 
Thanks,
Sid

**Comment by s8mathur** [comment]
Hi Benjamin, 
I have written a short PHP snippet to generate HTTP/2 requests using both `curl_init()` and `curl_multi_init()`. 
Summary: 

- PHP 7/8 + Curl 7.68.0 are working well with HTTP/2 servers in `curl_init()` mode - I suggest we stick to `curl_init()` only at this time in the plugin. Observed latencies are the same as network RTT between host and server - which is as good as it gets. 
- `curl_multi_init()` is showing very high delays - I have tried two HTTP/2 servers and the PHP-Curl implementation or my script is doing something wrong in both cases. So we should stay away from `CurlMultiHandle` until resolved. 

Gist is here, feel free to use :)
https://gist.github.com/s8mathur/c9697b0008d407f5f1b5b8f4c5f9da9b

**Comment by benjaminpick** [comment]
Again, I can't imagine this plugin would profit from multiplexing, as in most use cases, there will be only 1 Fastah request per PHP call.
Nmap RTT is ~220ms for me.
Yes we can replace wp_remote_get with curl_init. You can build it in by cloning my fastah branch.

**Comment by s8mathur** [comment]
Let's ship it the way it is now in the 'fastah' branch (your preferred v1 implementation). Once we get some real world usage, I will iterate on this based on user needs. Thank you.
