### ISSUE TITLE
AJAX: Suport for shortcodes

### ISSUE THREAD

**Issue by samunderwood** [yellowtree/geoip-detect#90]
Do shortcodes work when the AJAX endpoint is enabled? I edge-cache HTML on Cloudflare and am looking to inject certain pieces of content depending on country.

**Comment by benjaminpick** [comment]
No, not yet ... this feature is planned but not implemented yet.

Currently you could only implement the JS bits yourself.

**Comment by benjaminpick** [comment]
Support Phase 1:
- [ ] Simple shortcode: `[geoip_detect2]` (but properties skipCache ignored, ip not supported?)
- [ ] `[geoip_detect2_current_flag]`

Support Phase 2:
- [ ] `[geoip_detect2_countries_select]` incl. CF7
- [ ] `[geoip_detect2_text_input]` incl. CF7

Support Phase 3:
- [ ] `[geoip_detect2_show_if]`

No support:
- `[geoip_detect2_get_client_ip]`
- `[geoip_detect2_get_current_source_description]`
- `[geoip_detect2_get_external_ip_adress]`

**Comment by benjaminpick** [comment]
Support is complete now, it's in public beta ... 
https://github.com/yellowtree/geoip-detect/tree/4.0
