### ISSUE TITLE
country.isInEuropeanUnion not working ?!

### ISSUE THREAD

**Issue by zackdvd** [yellowtree/geoip-detect#93]
Hi! First of all great plugin, thanks for your work! This will be used for a charity.

I'm struggling with isInEuropeanUnion. I can get valid Information with 
```
[geoip_detect2_text_input name="city" property="country" lang="en" id="idc" class="class"]
[geoip_detect2_text_input name="city" property="continent" lang="en" id="idco" class="class"]
```
--> Germany / Europe.

But I do not get the information ineuropeanunion...

`[geoip_detect2 property="country.isInEuropeanUnion" lang="de" default="ihrem Land"]`

OR

`[geoip_detect2_show_if property="country.isInEuropeanUnion" property_value="true"] HALLO EU [/geoip_detect2_show_if]`

So it detects my country, but it is not mapped to function country.isInEuropeanUnion ? Or did I miss Brexit / Dexit? :-)

thank you!

**Comment by benjaminpick** [comment]
Hi,

Did you check if the property is working in the lookup page (Backend)?

**Comment by zackdvd** [comment]
Yes, no parameter in there. Is this parameter coming from IP-Lookupservice or inside the plugin (i would guess second)?

Example:
`
Key|Value
$record->city->name | Diemen
-- | --
$record->mostSpecificSubdivision->isoCode | NH
$record->mostSpecificSubdivision->name | North Holland
$record->subdivisions[0]->isoCode | NH
$record->subdivisions[0]->name | North Holland
$record->country->isoCode | NL
$record->country->geonameId | 2750405
$record->country->name | Netherlands
$record->continent->code | EU
$record->continent->name | Europe
$record->location->latitude | 52.309051513671875
$record->location->longitude | 4.940189838409424
$record->location->timeZone | Europe/Amsterdam
$record->traits->ipAddress | 51.137.13.106
$record->extra->currencyCode | EUR
$record->extra->original | [ 'ip' => '51.137.13.106', 'type' => 'ipv4', 'continent_code' => 'EU', 'continent_name' => 'Europe', 'country_code' => 'NL', 'country_name' => 'Netherlands', 'region_code' => 'NH', 'region_name' => 'North Holland', 'city' => 'Diemen', 'zip' => '1101', 'latitude' => 52.309051513671875, 'longitude' => 4.940189838409424, 'location' => [ 'geoname_id' => 2756888, 'capital' => 'Amsterdam', 'languages' => [ 0 => [ 'code' => 'nl', 'name' => 'Dutch', 'native' => 'Nederlands' ] ], 'country_flag' => 'http://assets.ipstack.com/flags/nl.svg', 'country_flag_emoji' => '', 'country_flag_emoji_unicode' => 'U+1F1F3 U+1F1F1', 'calling_code' => '31', 'is_eu' => true ] ]
$record->extra->flag |  
$record->extra->source | ipstack
$record->extra->cached | 0
$record->extra->error |  
$record->extra->countryIsoCode3 | NLD
$record->extra->tel | +31

`

**Comment by zackdvd** [comment]
Oh, there I see it, the parameter seems to be: "is_eu".
Do you do a mapping in your plugin?

**Comment by benjaminpick** [comment]
Normally this property should have been filled, yes. I fixed it in the
current beta (4.0.0-beta3) ...

Here is how you can install it:

https://github.com/yellowtree/geoip-detect/wiki/Beta-Testing

**Comment by zackdvd** [comment]
Oh wow, thank you!

**Comment by zackdvd** [comment]
I guess I was a bit early, sadly I've to say it's not working...
Shortcode not working and also no display on the lookup page. 

What I see in the code is that you are accessing the key is_eu differently.
$data['location']['is_eu'] and
$data['is_eu']

Could this be an issue?

`if (!empty($data['location']['is_eu'])) {
            $r['country']['is_in_european_union'] = $data['location']['is_eu'];
        }
        if (isset($data['is_eu']))
        $r['country']['is_in_european_union'] = $data['is_eu'];
                if (isset($data['timezone']['id']))
        $r['location']['time_zone'] = $data['timezone']['id'];`

**Comment by benjaminpick** [comment]
In my local installation it was working. Did you check the checkbox
"Skip Cache"? Because the plugin caches the ipstack results for 1 week
by default.

Yes you're right, the second is_eu call is wrong (it doesn't do anything)
