### ISSUE TITLE
Fatal error since plugin update

### ISSUE THREAD

**Issue by lanceadam** [yellowtree/geoip-detect#95]
Hello and thanks for the great plugin. Sadly today after the latest update my site reports the following error:

Fatal error: Declaration of YellowTree\GeoipDetect\DataSources\AbstractReader::country(string $ip): GeoIp2\Model\Country must be compatible with GeoIp2\ProviderInterface::country($ipAddress) in /dom28259/wp-content/plugins/geoip-detect/data-sources/abstract.php on line 94

**Plugin info:**
Retrieving Geo-Information using the Maxmind GeoIP (Lite) Database.
Version 4.0.0 | By Yellow Tree (Benjamin Pick) | View details

**Server Info**
WordPress 5.6.2 | PHP 7.3.21-1+ubuntu16.04.1+deb.sury.org+1 | Apache | MySQL 5.6.41-log

I am unable to activate the plugin, any help you could offer would be greatly appreciated.

**Comment by benjaminpick** [comment]
I just released 4.0.1, can you try?

And out of curiosity, are you using wordfence, WooCommerce, or another
plugin that also has Maxmind libraries? If so, which versions of these
plugins?

Benjamin

**Comment by lanceadam** [comment]
Hi Ben, 

Yes this seems to have fixed it and yes I use wordfence.

Kind Regards
Lance Redgrave | Managing Director


Level 1, 52-54 Willoughby Rd Crows Nest 2065

p(02) 9439 9115 <tel:0294399115> m0405 419 755 <tel:0405419755>
elance@redfoxmedia.com.au <mailto:lance@redfoxmedia.com.au>
www.redfoxmedia.com.au <http://www.redfoxmedia.com.au/> <http://www.linkedin.com/company/2622382>  <https://www.facebook.com/RedfoxMedia1>  <https://twitter.com/redfoxmedia1>  <https://plus.google.com/+RedfoxMediaAU/>  <http://redfoxmedia.com.au/rss/>
